# Config file for GFlows.
# See https://github.com/jbrunton/gflows#configuration for options.
templates:
  engine: jsonnet
  defaults:
    libs:
    - https://raw.githubusercontent.com/jbrunton/gflows-tests/develop/my-lib.gflowslib
